# Server settings (ServerProperties)
server:
  port: 8282
  ssl.key-store: classpath:server.jks
  ssl.key-store-password: 123456
  ssl.key-password: 1

  # address: localhost
  sessionTimeout: 30
  contextPath: /
# Tomcat specifics
tomcat:
  accessLogEnabled: false
  protocolHeader: x-forwarded-proto
  remoteIpHeader: x-forwarded-for
  basedir:
  backgroundProcessorDelay: 30 # secs
# logging
logging:
  path: ./log
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cup?characterEncoding=utf-8    
    username: auth
    password: auth
    driver-class: com.mysql.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    # Show or not log for each sql query
    show-sql: true
    # Hibernate ddl auto (create, create-drop, update)
    hibernate.ddl-auto: update
    properties:
      hibernate:
#        format_sql: true
        use_sql_comments: true
  resources:
    cache-period: 86400
